version: "2.2"
services:
  discovery:
    image: discovery
    ports:
      - "8761:8761"
    hostname: discovery
    networks:
      - ms-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      discovery:
        condition: service_started
    hostname: api-gateway
    networks:
      - ms-network
    environment:
      - server.port=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka

  common:
    image: common
    ports:
      - "8083:8083"
    depends_on:
      discovery:
        condition: service_started
    hostname: common
    networks:
      - ms-network
    environment:
      - server.port=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka

  first-service:
    image: first-service
    ports:
      - "8081:8081"
    depends_on:
      discovery:
        condition: service_started
    hostname: first-service
    networks:
      - ms-network
    environment:
      - server.port=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka

  second-service:
    image: second-service
    ports:
      - "8082:8082"
    depends_on:
      discovery:
        condition: service_started
    hostname: second-service
    networks:
      - ms-network
    environment:
      - server.port=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka

networks:
  ms-network:
    driver: bridge